[package]
name = "raw_preview_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"
reqwest = { version = "0.12.22", features = ["blocking"] }
flate2 = "1.1.2"
tar = "0.4"
